"""Step 3 - Run the SQL analytics showcase (sql/analytics/q*.sql).

Each .sql file holds ONE query answering ONE business question, with a header:
    -- Qxx · Title
    -- Question: ...
    -- Techniques: ...

Run:  python -m src.analytics      -> writes reports/sql_analytics.md
"""
from __future__ import annotations

from pathlib import Path

import duckdb
import pandas as pd

from src.build_warehouse import df_to_markdown
from src.config import PROJECT_ROOT, path
from src.db import connect, split_statements

ANALYTICS_DIR = PROJECT_ROOT / "sql" / "analytics"


def list_queries() -> list[str]:
    """Query names (file stems) in execution order."""
    return sorted(p.stem for p in ANALYTICS_DIR.glob("q*.sql"))


def _file(name: str) -> Path:
    return ANALYTICS_DIR / f"{name}.sql"


def query_header(name: str) -> dict:
    """Title, question, techniques and notes from the comment header."""
    header = {"title": name, "question": "", "techniques": "", "notes": ""}
    lines = _file(name).read_text(encoding="utf-8").splitlines()
    comment_lines = [l[2:].strip() for l in lines if l.startswith("--")]
    if comment_lines:
        header["title"] = comment_lines[0]
    current = None
    for line in comment_lines[1:]:
        low = line.lower()
        if low.startswith("question:"):
            current, header["question"] = "question", line.split(":", 1)[1].strip()
        elif low.startswith("techniques:"):
            current, header["techniques"] = "techniques", line.split(":", 1)[1].strip()
        elif low.startswith(("note:", "notes:")):
            current, header["notes"] = "notes", line.split(":", 1)[1].strip()
        elif current and line:
            header[current] += " " + line
    return header


def sql_text(name: str) -> str:
    """The SQL body without the comment header (for display)."""
    lines = _file(name).read_text(encoding="utf-8").splitlines()
    i = 0
    while i < len(lines) and lines[i].startswith("--"):
        i += 1
    return "\n".join(lines[i:]).strip()


def run_query(con: duckdb.DuckDBPyConnection, name: str) -> pd.DataFrame:
    stmts = split_statements(_file(name).read_text(encoding="utf-8"))
    return con.execute(stmts[-1]).df()


def main(preview_rows: int = 15) -> None:
    con = connect(read_only=True)
    parts = [
        "# SQL Analytics Showcase - results\n",
        "Generated by `python -m src.analytics` from `sql/analytics/`. "
        f"Each section shows the first {preview_rows} rows. Do not edit by hand.\n",
    ]
    try:
        for name in list_queries():
            h = query_header(name)
            df = run_query(con, name)
            print(f"{name}: {len(df):,} rows")
            parts.append(
                f"## {h['title']}\n\n**Question:** {h['question']}\n\n"
                f"**Techniques:** {h['techniques']}\n\n"
                + (f"**Notes:** {h['notes']}\n\n" if h["notes"] else "")
                + f"Rows returned: {len(df):,}\n\n{df_to_markdown(df.head(preview_rows))}\n"
            )
    finally:
        con.close()
    out = path("reports_dir") / "sql_analytics.md"
    out.write_text("\n".join(parts), encoding="utf-8")
    print(f"Report -> {out}")


if __name__ == "__main__":
    main()
