"""Steps 1-2 - Build the DuckDB warehouse and the data-quality report.

Order:
  1. raw.transactions      <- data/interim/transactions.parquet (from src.ingest)
  2. sql/01_staging.sql    typed + flagged lines, nothing dropped
  3. sql/02_data_quality.sql  -> reports/data_quality.md
  4. sql/03_core_model.sql star schema
  5. sql/checks/core_summary.sql -> appended to the report

Run:  python -m src.build_warehouse
"""
from __future__ import annotations

import sys

import pandas as pd

from src.config import path, sql_path
from src.db import connect, run_named_queries, run_sql_file


def df_to_markdown(df: pd.DataFrame) -> str:
    """Minimal markdown table writer (avoids an extra 'tabulate' dependency)."""
    def fmt(v):
        if pd.isna(v):
            return ""
        if isinstance(v, float):
            return f"{v:,.2f}"
        if isinstance(v, int):
            return f"{v:,}"
        return str(v)

    header = "| " + " | ".join(map(str, df.columns)) + " |"
    sep = "| " + " | ".join("---" for _ in df.columns) + " |"
    rows = ["| " + " | ".join(fmt(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join([header, sep, *rows])


def render_section(queries: list[dict]) -> str:
    parts = []
    for q in queries:
        parts.append(f"### {q['title']}\n\n{df_to_markdown(q['df'])}\n")
    return "\n".join(parts)


def main() -> None:
    parquet = path("interim_parquet")
    if not parquet.exists():
        sys.exit(f"{parquet} not found. Run `python -m src.ingest` first.")

    con = connect()
    try:
        for schema in ("raw", "staging", "core", "marts"):
            con.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")

        print("1/5 loading raw.transactions ...")
        con.execute(
            "CREATE OR REPLACE TABLE raw.transactions AS "
            f"SELECT * FROM read_parquet('{parquet.as_posix()}')"
        )

        print("2/5 building staging.lines ...")
        run_sql_file(con, sql_path("staging"))

        print("3/5 running data-quality checks ...")
        dq = run_named_queries(con, sql_path("data_quality"))

        print("4/5 building core star schema ...")
        run_sql_file(con, sql_path("core"))

        print("5/5 running core summary checks ...")
        summary = run_named_queries(con, sql_path("core_summary"))
    finally:
        con.close()

    report = path("reports_dir") / "data_quality.md"
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(
        "# Data Quality Report - UCI Online Retail II\n\n"
        "Generated by `python -m src.build_warehouse` from `sql/02_data_quality.sql` "
        "and `sql/checks/core_summary.sql`. Do not edit by hand.\n\n"
        "## Part A - Raw and staging profile\n\n"
        + render_section(dq)
        + "\n## Part B - Core model checks\n\n"
        + render_section(summary),
        encoding="utf-8",
    )
    print(f"Done. Report -> {report}")


if __name__ == "__main__":
    main()
